---
title: "Lourdes Orozco"
author: "Math_115"
date: "Spring Semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  
And this was odd, because it was  
The middle of the night.  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
I wandered lonely as a cloud  
That floats on high o'er vales and hills,  
When all at once I saw a crowd,  
A host, of golden daffodils;  
Beside the lake, beneath the trees,  
Fluttering and dancing in the breeze.  

Continuous as the stars that shine  
And twinkle on the milky way,  
They stretched in never-ending line  
Along the margin of a bay:  
Ten thousand saw I at a glance,  
Tossing their heads in sprightly dance.  
